### PR TITLE
Feature/german

### PR DESCRIPTION
**Pull request by Erendel**

### CODE REVIEW

**Comment by Marat-Tanalin** [comment]
Thanks, @Erendel, will check your translation in a few days.

**Comment by Marat-Tanalin** [comment]
Thanks, the translation looks fine in general. There are some things that need clarification or fixing though:

* `Common.Video`, `Settings.Compatibility.ppu.Video`: "Video" is translated as "Bild". Machine translation translates it back to English as "Image" or "Screen"/"Display" instead of something like "Video". Direct machine translation from English to German is the same "Video" as in English. Wouldn’t "Video" be a more correct translation? Especially given that you translated "video" as "video" in the `Settings.Audio.Skew.tooltip` string. (I’m aware of machine-translation limitations and drawbacks and don’t consider its results as canonical and/or better than manual human translation, machine translation is just the only source of information for me given that I don’t speak German, while I’m trying to make sure everything is OK and to understand the nature of things in general.)

* `Settings.Common.FrameLowercase = "Bild"` — the English string "frame" is lowercase, so the translation should probably be lowercase too. Also, the "Bild" word is used again, now for "frame", previously for "video". Maybe a less ambiguous translation is possible: for example, machine translation suggests the German word "einzelbild" that traslates to English as "single frame/image" which seems OK. Same with:
  - `Settings.Emulator.FastForward.FrameSkip.Frames2to4` ("|" is automatically replaced with a number when the string is displayed, so the word in the translation string is **not** first in the sentence);
  - `Settings.Emulator.FastForward.FrameSkip.Frames`;
  - `Settings.Emulator.Rewind.Length.states`;
  - `Settings.Compatibility.ppu.Video`.

* `Settings.Compatibility.cpu.Processor` — the translation is capitalized. The original string is lowercase, so the translation should probably be lowercase too ("prozessor" instead of "Prozessor").

* `Settings.Compatibility.dsp.Audio` — the translation is capitalized again while the original string is lowercase.

* `Settings.Audio.Skew` — "Skew" is translated as "Versatz" that translates back to English as "Offset". It would probably make sense to translate it as if the original English string was "Rate" (as in "Sample rate") or maybe "Rate offset" instead of "Skew". (I’m considering replacing the English term "Skew" with "Rate" or "Rate offset" too for more clarity.)

* `Settings.Drivers` (plural "Drivers") and `Settings.Drivers.Driver` (singular "Driver") are translated as the same "Treiber" word. Is this correct, doesn’t German have a way to express plural words?

* `Settings.Drivers.Video.GpuSync.tooltip`, `StatusIcon.verifiedRom.tooltip` — there is a space between the number and "%" in the translation while there is no space in the original English string. Is this intentional and common in German?

* `Tools.StateManager = "Zwischenstandsverwaltung"` — there are no spaces between words. Is this intentional? Wouldn’t something like "Zwischen stands verwaltung" be more correct?

* `Browser.Delete.FailedToDelete` — the translated string contains triple "???" while the original string contains just one "?". What’s the reason of that tripling?

* Some translated strings (see the full list below in spoiler) contain mixed case of first characters in words while in the original string everything except first character in each sentence is lowercase. Does capitalization have some special meaning in German, or was this not intended? If the latter, the German translation should probably have the same case of words as the original English string. It’s OK (and even may make sense if that matches the established practices in the specific language) to remove capitalization (like you did e.g. in the `Movies.PlayMovie` string) used in original English string; but if the original English string didn’t contain capitalization, it’s generally unreasonable to _add_ capitalization as long as the language does not _require_ capitalization for the word to have specific _meaning_. For what it’s worth, I’m considering dropping capitalization at all across the entire user interface. <details><summary>_The affected strings (click to view)_</summary>
  - `Common.AreYouSure`
  - `Menu.File.OpenRecentGame.ClearList.confirm.title`
  - `Menu.File.OpenRecentGame.ClearList.confirm`
  - `Settings.Common.PressKeyOrButtonForMapping`
  - `Settings.Video.DimVideoWhenIdle.tooltip`
  - `Settings.Audio.Skew.tooltip`
  - `Settings.Audio.Volume.tooltip`
  - `Settings.Audio.Balance.tooltip`
  - `Settings.Input.WhenFocusIsLost`
  - `Settings.Input.TurboRate.tooltip`
  - `Settings.Hotkeys.CombinationalLogic`
  - `Settings.Hotkeys.CombinationalLogic.tooltip`
  - `Settings.Hotkeys.CombinationalLogic.And.tooltip`
  - `Settings.Hotkeys.CombinationalLogic.Or.tooltip`
  - `Settings.Hotkeys.Rewind.enableFirst`
  - `Settings.Paths.SameAsLoadedGame`
  - `Settings.Emulator.General.warnOnUnverifiedGames`
  - `Settings.Emulator.General.autoSaveStateOnUnload`
  - `Settings.Emulator.General.AutoResumeOnLoad`
  - `Settings.Emulator.General.UseNativeFileDialogs`
  - `Settings.Emulator.FastForward.FrameSkip.tooltip`
  - `Settings.Emulator.FastForward.Limiter.tooltip`
  - `Settings.Emulator.FastForward.mute`
  - `Settings.Emulator.Rewind.Frequency.everyFrames`
  - `Settings.Emulator.Rewind.Length.states`
  - `Settings.Enhancements.FastMode`
  - `Settings.Enhancements.Ppu.NoSpriteLimit`
  - `Settings.Enhancements.Dsp.CubicInterpolation`
  - `Settings.Enhancements.Coprocessors.PreferHle`
  - `Settings.Enhancements.Coprocessors.PreferHle.tooltip`
  - `Settings.Enhancements.GameEnhancements.Hotfixes.tooltip`
  - `Settings.Compatibility.entropy`
  - `Settings.Compatibility.entropy.None.tooltip`
  - `Settings.Compatibility.entropy.Low.tooltip`
  - `Settings.Compatibility.entropy.High.tooltip`
  - `Settings.Compatibility.cpu.FastMath`
  - `Settings.Compatibility.cpu.FastMath.tooltip`
  - `Settings.Compatibility.ppu.NoVramBlocking`
  - `Settings.Compatibility.ppu.NoVramBlocking.tooltip`
  - `Settings.Compatibility.dsp.EchoShadowRam.tooltip`
  - `Settings.Drivers.ExclusiveMode`
  - `Settings.Drivers.ActiveDriver`
  - `Settings.Drivers.changeConfirm`
  - `Settings.noteGameRestart`
  - `Settings.Drivers.Video.failedToInitialize`
  - `Settings.Drivers.Video.FullScreenMonitor`
  - `Settings.Drivers.Video.FullScreenMonitor.tooltip`
  - `Settings.Drivers.Video.ExclusiveMode.tooltip`
  - `Settings.Drivers.Video.Synchronize.tooltip`
  - `Settings.Drivers.Video.GpuSync`
  - `Settings.Drivers.Video.GpuSync.tooltip`
  - `Settings.Drivers.Audio.failedToInitialize`
  - `Settings.Drivers.Audio.ExclusiveMode.tooltip`
  - `Settings.Drivers.Audio.Synchronize.tooltip`
  - `Settings.Drivers.Audio.DynamicRate`
  - `Settings.Drivers.Audio.DynamicRate.tooltip`
  - `Settings.Drivers.Input.failedToInitialize`
  - `Settings.Drivers.Input.Reload.tooltip`
  - `Settings.Drivers.syncModePresets.AdaptiveSync.failure`
  - `Settings.Drivers.syncModePresets.AdaptiveSync.success`
  - `Settings.Drivers.syncModePresets.DynamicRateControl.failure`
  - `Tools.LoadState.SelectedStateSlot`
  - `Tools.LoadState.RemoveAllStates.confirm.title`
  - `Tools.LoadState.RemoveAllStates.confirm`
  - `Tools.CheatEditor.remove.confirm`
  - `Tools.CheatEditor.noCheats`
  - `Tools.CheatEditor.EnableCheats.tooltip`
  - `Tools.CheatEditor.EnableCheats.disabled`
  - `Tools.CheatEditor.EnableCheats.enabled`
  - `Tools.CheatEditor.invalidFormat`
  - `Tools.StateManager.remove.confirm`
  - `Game.VerifiedGameOpened`
  - `Game.AndPatchApplied`,
  - `Game.GameOpeningCancelled`
  - `Game.unverifiedGameWarning.title`
  - `Game.unverifiedGameWarning`
  - `Game.unverifiedGameWarning.alwaysQuestion`
  - `Program.Open.MissingRequiredData`
  - `Browser.ChooseFolder`
  - `Browser.Rename.EnterNewFolderName`
  - `Browser.Rename.EnterNewFileName`
  - `Browser.Create.EnterName`
  - `Browser.CreateFolder.EnterNewFolderName`
  - `Browser.Delete.FailedToDelete`
  - `Browser.Delete.confirm`
  - `Browser.Delete.confirm.item`
  - `Browser.Delete.confirm.items`
  - `StatusIcon.verifiedRom.tooltip`
  - `StatusIcon.unverifiedRom.tooltip`
  - `ResetDrivers.message`
  - `States.incompatibleFormat`
  - `States.UnableToWriteToDisk`
  - `Patch.ipsWarning`
  - `Patch.ensureHeaderless`
  - `Movies.formatNotSupported`</details>

**Comment by Erendel** [comment]
Thanks for the input!

German is particular concerning capitalization. In general nouns and poper names are written capitalized. Then there is the German "Sie" which is a formal way of addressing somebody and translates to "you" and is always written in capitalized. There is also an informal translation of "you", which is "du" and can be lowercase. "Sie" can be used as singular and plural, "du" on the other hand just as singular. There are special cases for nominalized adjectives, verbs and numbers, too. I probably forgot something. It’s complicated ;).
This should address most of your questions regarding capitalization. I still looked at each of them individually.

- `Common.Video, Settings.Compatibility.ppu.Video` — Thanks for pointing out the inconsistency. "Video" in the context of settings can be translated as both "Bild" and "Video" (e.g. video settings can be translated as both "Bildeinstellungen" and "Videoeinstellungen"). Concerning the overlap with the translation for "frame" I would agree with you and keep "Video" as the translation.

- `Settings.Common.FrameLowercase` = "Bild" — The translation for "frame" is capitalized as it is a noun. German language quirks. I alternate between "Bild" and "Einzelbild" in the translation as "Bild" is shorter and depending on the context still unambiguous. In all other contexts the translation will be "Einzelbild". I guessed that the "|" was just a placeholder element ;).

- `Settings.Audio.Skew` — The German translation for "audio skew" is "Audio-Versatz" or "Audioverzerrung". Since "Verzerrung" translates back as "distortion" and there should be a difference to "skew", I went with "Versatz".

- `Settings.Drivers` and `Settings.Drivers.Driver` — Singular and plural are the same for some German words. "Treiber" just so happens to be one of them.

- `Settings.Drivers.Video.GpuSync.tooltip`, `StatusIcon.verifiedRom.tooltip` — The space before % was unintentional. Just a trailing space left by my way of translating. Thanks.

- `Tools.StateManager` = "Zwischenstandsverwaltung" — In German you can string nouns together without spaces to form a new word if all nouns are used to describe one object in particular. Capitalization is dropped for all nouns after the first.

- `Browser.Delete.FailedToDelete` — I retranslated this sentence a few times and forgot to delete the "?" each time :D.

As you can imagine, dropping capitalization across the user interface would be a bit troublesome for the German language. To a German it would look quite odd if everything was lowercase.
Everything in uppercase on the other hand would work. But I think it would feel like the whole UI was screaming at you all the time.

Let me know if there are any other issues.

And thanks again. For the input and for your work on bsnes-mt. It is very much appreciated.

**Comment by Marat-Tanalin** [comment]
Oh, I accidentally manually commited the file instead of accepting your pull request (somewhat used to do this while working on the Spanish translation). On the other hand, this makes the commit history somewhat cleaner. Is that OK for you?

Thank you for your contribution, @Erendel.

**Comment by Marat-Tanalin** [comment]
Decided to delete the manually committed file and merge your PR instead, so that you are displayed in the “Contributors” list of the repo.

**Comment by Marat-Tanalin** [comment]
Included in the [1.3.3r2](https://github.com/Marat-Tanalin/bsnes-mt/releases/tag/1.3.3) release.

**Pull request merged**
